"""empty message

Revision ID: 443bbe15147b
Revises: 
Create Date: 2021-04-28 22:06:05.901237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443bbe15147b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabekg_dispatchers', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('tabekg_dispatchers', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('tabekg_dispatchers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tabekg_dispatchers', 'tabekg_users', ['user_id'], ['id'])
    op.drop_column('tabekg_dispatchers', 'full_name')
    op.drop_column('tabekg_dispatchers', 'phone_number')
    op.add_column('tabekg_users', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('tabekg_users', sa.Column('last_action', sa.DateTime(), nullable=True))
    op.add_column('tabekg_users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'tabekg_users', ['phone_number'])
    op.drop_column('tabekg_users', 'email')
    op.drop_column('tabekg_users', 'password')
    op.drop_column('tabekg_users', 'name')
    op.drop_column('tabekg_users', 'status')
    op.drop_column('tabekg_users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabekg_users', sa.Column('role', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('tabekg_users', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('tabekg_users', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('tabekg_users', sa.Column('password', sa.VARCHAR(length=192), autoincrement=False, nullable=False))
    op.add_column('tabekg_users', sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tabekg_users', type_='unique')
    op.drop_column('tabekg_users', 'phone_number')
    op.drop_column('tabekg_users', 'last_action')
    op.drop_column('tabekg_users', 'full_name')
    op.add_column('tabekg_dispatchers', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tabekg_dispatchers', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tabekg_dispatchers', type_='foreignkey')
    op.drop_column('tabekg_dispatchers', 'user_id')
    op.drop_column('tabekg_dispatchers', 'date_modified')
    op.drop_column('tabekg_dispatchers', 'date_created')
    # ### end Alembic commands ###
