"""empty message

Revision ID: b3f843f946a8
Revises: ff486811f169
Create Date: 2021-04-28 22:39:10.925734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3f843f946a8'
down_revision = 'ff486811f169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabekg_users', 'user_type',
               existing_type=postgresql.ENUM('taxi', 'dispatcher', name='usertypes'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabekg_users', 'user_type',
               existing_type=postgresql.ENUM('taxi', 'dispatcher', name='usertypes'),
               nullable=True)
    # ### end Alembic commands ###
