"""empty message

Revision ID: ff486811f169
Revises: 443bbe15147b
Create Date: 2021-04-28 22:37:11.016758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff486811f169'
down_revision = '443bbe15147b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabekg_dispatchers')
    op.add_column('tabekg_users', sa.Column('user_type', sa.Enum('taxi', 'dispatcher', name='usertypes'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabekg_users', 'user_type')
    op.create_table('tabekg_dispatchers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tabekg_users.id'], name='tabekg_dispatchers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tabekg_dispatchers_pkey')
    )
    # ### end Alembic commands ###
